ignore = [
  "/data"
]
blank_lines_upper_bound = 2
edition = "2024"
hard_tabs = true
max_width = 140
use_small_heuristics = "Max"
imports_granularity = "Module"
#Probably not needed because hard_tabs
tab_spaces = 2
