[package]
name = "server"
version = "0.5.0"
edition = "2024"
default-run = "server"

[dependencies]
lib = {path = "../lib", version = "*"}
data = {path = "../data/main", version = "*"}
flate2 = "1.1.2"
dashmap = "6"
